export const ASSIGNMENT_STATUS = {
    NEW: "new",
    IN_PROGRESS: "in_progress",
    COMPLETED: "completed",
    LATE: "late",
};

export const ASSIGNMENT_PRIORITY = {
    LOW: "low",
    MEDIUM: "medium",
    HIGH: "high",
};

export const mockAssignments = [
    {
        id: "assignment-001",
        title: "Luyện phát âm âm /θ/",
        description:
            "Giảng viên yêu cầu luyện lại các từ chứa âm /θ/ vì kết quả trước đó cho thấy bạn thường phát âm nhầm thành /t/ hoặc /s/.",
        teacherName: "Ms. Emily Carter",
        studentName: "Nguyen Van A",
        createdAt: "2026-04-27T09:00:00.000Z",
        deadline: "2026-05-04T23:59:59.000Z",
        priority: ASSIGNMENT_PRIORITY.HIGH,
        status: ASSIGNMENT_STATUS.NEW,
        isNew: true,
        items: [
            {
                id: "item-001",
                type: "word",
                text: "think",
                transcript: "think",
                targetPhoneme: "θ",
                errorType: "substitution",
                previousScore: 62,
                completed: false,
                latestScore: null,
                note: "Đặt đầu lưỡi nhẹ giữa hai hàm răng, đẩy hơi ra đều.",
            },
            {
                id: "item-002",
                type: "word",
                text: "thank",
                transcript: "thank",
                targetPhoneme: "θ",
                errorType: "substitution",
                previousScore: 58,
                completed: false,
                latestScore: null,
                note: "Không đọc thành /tæŋk/. Tập trung vào âm gió /θ/ ở đầu từ.",
            },
            {
                id: "item-003",
                type: "sentence",
                text: "I think this is a good idea.",
                transcript: "I think this is a good idea.",
                targetPhoneme: "θ",
                errorType: "weak_articulation",
                previousScore: 65,
                completed: false,
                latestScore: null,
                note: "Tập trung vào think và this, không nuốt âm đầu.",
            },
        ],
        progress: {
            completedItems: 0,
            totalItems: 3,
            percent: 0,
            averageScore: null,
        },
        results: [],
        teacherFeedback: "",
    },
    {
        id: "assignment-002",
        title: "Phân biệt /ʃ/ và /s/",
        description:
            "Luyện lại các từ có âm /ʃ/. Bạn đang có xu hướng phát âm /ʃ/ thành /s/ trong một số từ.",
        teacherName: "Mr. David Lee",
        studentName: "Nguyen Van A",
        createdAt: "2026-04-26T14:30:00.000Z",
        deadline: "2026-05-02T23:59:59.000Z",
        priority: ASSIGNMENT_PRIORITY.MEDIUM,
        status: ASSIGNMENT_STATUS.IN_PROGRESS,
        isNew: false,
        items: [
            {
                id: "item-004",
                type: "word",
                text: "ship",
                transcript: "ship",
                targetPhoneme: "ʃ",
                errorType: "substitution",
                previousScore: 60,
                completed: true,
                latestScore: 78,
                note: "Không đọc thành sip. Làm tròn môi nhẹ khi phát âm /ʃ/.",
            },
            {
                id: "item-005",
                type: "word",
                text: "she",
                transcript: "she",
                targetPhoneme: "ʃ",
                errorType: "weak_articulation",
                previousScore: 66,
                completed: false,
                latestScore: null,
                note: "Giữ âm gió dài hơn, môi hơi tròn.",
            },
            {
                id: "item-006",
                type: "sentence",
                text: "She sells fresh fish.",
                transcript: "She sells fresh fish.",
                targetPhoneme: "ʃ",
                errorType: "contrast_error",
                previousScore: 64,
                completed: false,
                latestScore: null,
                note: "Phân biệt rõ she /ʃiː/ và sells /selz/.",
            },
        ],
        progress: {
            completedItems: 1,
            totalItems: 3,
            percent: 33,
            averageScore: 78,
        },
        results: [
            {
                id: "result-001",
                itemId: "item-004",
                score: 78,
                submittedAt: "2026-04-27T10:15:00.000Z",
                audioUrl: null,
                phonemeErrors: [
                    {
                        phoneme: "ʃ",
                        expected: "ʃ",
                        actual: "s",
                        suggestion: "Làm tròn môi nhẹ và đẩy hơi mềm hơn.",
                    },
                ],
            },
        ],
        teacherFeedback: "Em đã cải thiện ở từ ship, tiếp tục luyện thêm she và câu hoàn chỉnh.",
    },
    {
        id: "assignment-003",
        title: "Luyện trọng âm câu ngắn",
        description:
            "Luyện lại các câu ngắn để cải thiện nhịp điệu, trọng âm và độ tự nhiên khi nói.",
        teacherName: "Ms. Emily Carter",
        studentName: "Nguyen Van A",
        createdAt: "2026-04-25T08:45:00.000Z",
        deadline: "2026-04-30T23:59:59.000Z",
        priority: ASSIGNMENT_PRIORITY.LOW,
        status: ASSIGNMENT_STATUS.IN_PROGRESS,
        isNew: false,
        items: [
            {
                id: "item-007",
                type: "sentence",
                text: "Can you help me with this?",
                transcript: "Can you help me with this?",
                targetPhoneme: null,
                errorType: "sentence_stress",
                previousScore: 70,
                completed: true,
                latestScore: 82,
                note: "Nhấn nhẹ vào help và this.",
            },
            {
                id: "item-008",
                type: "sentence",
                text: "I would like a cup of coffee.",
                transcript: "I would like a cup of coffee.",
                targetPhoneme: null,
                errorType: "rhythm",
                previousScore: 68,
                completed: false,
                latestScore: null,
                note: "Giữ nhịp đều, không đọc từng từ rời rạc.",
            },
        ],
        progress: {
            completedItems: 1,
            totalItems: 2,
            percent: 50,
            averageScore: 82,
        },
        results: [
            {
                id: "result-002",
                itemId: "item-007",
                score: 82,
                submittedAt: "2026-04-27T11:00:00.000Z",
                audioUrl: null,
                phonemeErrors: [],
            },
        ],
        teacherFeedback: "",
    },
];