name: Supabase Keep Alive

on:
  schedule:
    # Chạy vào lúc 00:00 ngày mùng 1, 5, 9, 13, 17, 21, 25, 29 hàng tháng
    - cron: '0 0 */4 * *'
  workflow_dispatch: # Cho phép nhấn nút chạy thủ công để kiểm tra

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send a request to Supabase
        run: |
          curl -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
